### ISSUE TITLE
setup: "try me" link won't work for anyone that doesn't have push access

### ISSUE THREAD

**Issue by antislice** [graysonwright/osbot#18]
> Visit http://localhost:3000/gh/graysonwright/osbot to see the site in action.

Best fix IMO: change link in readme to `<your-username>/osbot`, & make it clear that you should fork the repo, not clone it.

What I got:

```
GET https://api.github.com/repos/graysonwright/osbot/collaborators?per_page=100: 403 - Must have push access to view repository collaborators. // See: https://developer.github.com/v3

app/models/repo.rb:46:in `block in collaborators'
app/models/repo.rb:108:in `cache'
app/models/repo.rb:45:in `collaborators'
app/models/repo.rb:51:in `collaborator_with_handle'
app/models/repo.rb:36:in `contributor_for_handle'
app/models/repo.rb:15:in `map'
app/models/repo.rb:15:in `block in contributors'
app/models/repo.rb:108:in `cache'
app/models/repo.rb:13:in `contributors'
app/views/contributors/index.html.erb:4:in `_app_views_contributors_index_html_erb__1932456128199212103_70353805976940'
```

**Comment by c-lliope** [comment]
oh wow, that's great to know. I think the repo access logic will change when we implement GitHub Oauth in #16, so I might wait to merge that before rewriting the instructions.
